version: "3.7"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD={{GRAFANA_ADMIN_PASSWORD}}
      - GF_USERS_ALLOW_SIGN_UP=false
      - NODE_ENV=development
      - GF_SERVER_ROOT_URL=https://{{GRAFANA_DOMAIN}}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=ick-buttontable-panel,GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=yesoreyeram-boomtheme-panel
      - GF_AUTH_GOOGLE_SCOPES=openid email profile https://www.googleapis.com/auth/webmasters
      - GF_AUTH_GOOGLE_AUTH_URL=https://accounts.google.com/o/oauth2/v2/auth
      - GF_AUTH_GOOGLE_TOKEN_URL=https://oauth2.googleapis.com/token
      - GF_AUTH_GOOGLE_API_URL=https://openidconnect.googleapis.com/v1/userinfo
      - GF_RENDERING_SERVER_URL=http://grafana.demodomain.dev:8081/render
      - GF_RENDERING_CALLBACK_URL=https://{{GRAFANA_DOMAIN}}
      - GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=true
      - GF_LOG_FILTERS=rendering:debug
      - GF_RENDERING_TOKEN={{GRAFANA_RENDERING_TOKEN}}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./plugins:/var/lib/grafana/plugins
    networks:
      - {{NETWORK}}
networks:
  {{NETWORK}}:
    external: true
    name: {{NETWORK}}
volumes:
  grafana_data:
    external: true
