global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'n8n'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['{{SUBDOMAIN}}.{{N8N_DOMAIN_NAME}}:5678']
  - job_name: 'supabase-db'
    static_configs:
      - targets: ['localhost:9187']
    metrics_path: '/metrics'
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
